Repository hashgraph/hedera-transaction-tool, pull requests merged in 2024-12, with the labels that each got.

#1294 ci: Roll-back of codecov version due to issues with latest one. #395
  .github/workflows/test-backend.yaml
  .github/workflows/test-frontend.yaml
Labels: github_actions

#1329 test: Add tests for group tx in personal mode
  automation/README.md
  automation/pages/GroupPage.js
  automation/pages/RegistrationPage.js
  automation/tests/groupTransactionTests.test.js
  automation/utils/databaseQueries.js
  automation/utils/databaseUtil.js
  front-end/docs/api.md
  front-end/src/renderer/components/EmptyTransactions.vue
  front-end/src/renderer/components/Transaction/TransactionGroupProcessor.vue
  front-end/src/renderer/components/Transaction/TransactionHeaderControls.vue
  front-end/src/renderer/pages/CreateTransactionGroup/CreateTransactionGroup.vue
  front-end/src/tests/main/windows/mainWindow.spec.ts
Labels: QA

#1374 chore: add repo maintainers in the CODEOWNERS file
  .github/CODEOWNERS
Labels: Audit
